version: "3.0"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        expose: 
            - "2181"
        restart: always
        container_name: zookeeper

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9093:9093"
        expose:
            - "9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        restart: always
        container_name: kafka
    
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        container_name: redis

    cli2cloud-service:
        depends_on:
            - kafka
            - redis
        build: ./service
        ports:
            - "8080:8080"
        container_name: cli2cloud-service

