version: "3.0"
services:
    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres
        volumes:
            - /root/db_data:/var/lib/postgresql/data
        build: ./management
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=cli2cloud
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=1234
    
    cli2cloud-service:
      depends_on:
        - postgres
      build: ./service
      ports:
        - "8080:8080"
      container_name: cli2cloud-service
