version: "3.9"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    volumes:
      - ./management/postgres/postgres_data:/var/lib/postgresql/data
    build: ./management/postgres/
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=cli2cloud
      - POSTGRES_PASSWORD=$DB_PWD
      - POSTGRES_DB=cli2cloud

  backend:
    container_name: backend
    ports: 
      - "50051:50051"
    depends_on:
      - postgres
    build: ./service
    environment:
      - POSTGRES_PASSWORD=$DB_PWD

  envoy:
    build: ./management/proxies
    ports:
      - "8000:8000"

